version: "3.9"

services:
  service1:
    build: service1
    image: alexmilis/service1
    ports:
      - "8080:8080"
  service2:
    build: service2
    image: alexmilis/service2
    ports:
      - "8081:8080"
    depends_on:
      - service1