apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: alexmilis/service1:latest
        ports:
        - containerPort: 80
